/*
 * Icon registry. Flux renders Heroicons, so the same icon names map onto
 * @heroicons/react: "outline" (24px), "mini" (20px solid), "micro" (16px solid).
 */
import {
    HomeIcon as HomeO,
    Squares2X2Icon as Squares2X2O,
    PlusCircleIcon as PlusCircleO,
    TagIcon as TagO,
    ArrowDownTrayIcon as ArrowDownTrayO,
    DocumentTextIcon as DocumentTextO,
    UsersIcon as UsersO,
    ChartBarIcon as ChartBarO,
    BanknotesIcon as BanknotesO,
    StarIcon as StarO,
    IdentificationIcon as IdentificationO,
    InboxArrowDownIcon as InboxArrowDownO,
    CheckBadgeIcon as CheckBadgeO,
    FlagIcon as FlagO,
    EyeIcon as EyeO,
    EyeSlashIcon as EyeSlashO,
    ArrowPathIcon as ArrowPathO,
    CreditCardIcon as CreditCardO,
    Cog6ToothIcon as Cog6ToothO,
    ClipboardDocumentListIcon as ClipboardDocumentListO,
    AcademicCapIcon as AcademicCapO,
    CalendarIcon as CalendarO,
    BellIcon as BellO,
    UserIcon as UserO,
    BriefcaseIcon as BriefcaseO,
    ShieldCheckIcon as ShieldCheckO,
    MagnifyingGlassIcon as MagnifyingGlassO,
    ArrowRightStartOnRectangleIcon as ArrowRightStartOnRectangleO,
    Bars3Icon as Bars3O,
    XMarkIcon as XMarkO,
    ChevronRightIcon as ChevronRightO,
    ChevronDownIcon as ChevronDownO,
    InformationCircleIcon as InformationCircleO,
    CheckIcon as CheckO,
    CheckCircleIcon as CheckCircleO,
    ArrowRightIcon as ArrowRightO,
    ArrowLeftIcon as ArrowLeftO,
    ClockIcon as ClockO,
    ExclamationTriangleIcon as ExclamationTriangleO,
    XCircleIcon as XCircleO,
    LockClosedIcon as LockClosedO,
    RectangleStackIcon as RectangleStackO,
    SignalIcon as SignalO,
    ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareO,
    ChatBubbleLeftRightIcon as ChatBubbleLeftRightO,
    KeyIcon as KeyO,
    UserGroupIcon as UserGroupO,
    CpuChipIcon as CpuChipO,
    WrenchScrewdriverIcon as WrenchScrewdriverO,
    ServerStackIcon as ServerStackO,
    DocumentArrowDownIcon as DocumentArrowDownO,
    PlusIcon as PlusO,
    ReceiptPercentIcon as ReceiptPercentO,
    InboxIcon as InboxO,
    UserPlusIcon as UserPlusO,
    DocumentIcon as DocumentO,
    ArrowUpTrayIcon as ArrowUpTrayO,
    ChatBubbleLeftIcon as ChatBubbleLeftO,
    TrashIcon as TrashO,
    FingerPrintIcon as FingerPrintO,
    QrCodeIcon as QrCodeO,
    DocumentDuplicateIcon as DocumentDuplicateO,
    ArrowUturnLeftIcon as ArrowUturnLeftO,
} from '@heroicons/react/24/outline';
import {
    HomeIcon as HomeM,
    Squares2X2Icon as Squares2X2M,
    PlusCircleIcon as PlusCircleM,
    TagIcon as TagM,
    ArrowDownTrayIcon as ArrowDownTrayM,
    DocumentTextIcon as DocumentTextM,
    UsersIcon as UsersM,
    ChartBarIcon as ChartBarM,
    BanknotesIcon as BanknotesM,
    StarIcon as StarM,
    IdentificationIcon as IdentificationM,
    InboxArrowDownIcon as InboxArrowDownM,
    CheckBadgeIcon as CheckBadgeM,
    FlagIcon as FlagM,
    EyeIcon as EyeM,
    EyeSlashIcon as EyeSlashM,
    ArrowPathIcon as ArrowPathM,
    CreditCardIcon as CreditCardM,
    Cog6ToothIcon as Cog6ToothM,
    ClipboardDocumentListIcon as ClipboardDocumentListM,
    AcademicCapIcon as AcademicCapM,
    CalendarIcon as CalendarM,
    BellIcon as BellM,
    UserIcon as UserM,
    BriefcaseIcon as BriefcaseM,
    ShieldCheckIcon as ShieldCheckM,
    MagnifyingGlassIcon as MagnifyingGlassM,
    ArrowRightStartOnRectangleIcon as ArrowRightStartOnRectangleM,
    Bars3Icon as Bars3M,
    XMarkIcon as XMarkM,
    ChevronRightIcon as ChevronRightM,
    ChevronDownIcon as ChevronDownM,
    InformationCircleIcon as InformationCircleM,
    CheckIcon as CheckM,
    CheckCircleIcon as CheckCircleM,
    ArrowRightIcon as ArrowRightM,
    ArrowLeftIcon as ArrowLeftM,
    ClockIcon as ClockM,
    ExclamationTriangleIcon as ExclamationTriangleM,
    XCircleIcon as XCircleM,
    LockClosedIcon as LockClosedM,
    RectangleStackIcon as RectangleStackM,
    SignalIcon as SignalM,
    ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareM,
    ChatBubbleLeftRightIcon as ChatBubbleLeftRightM,
    KeyIcon as KeyM,
    UserGroupIcon as UserGroupM,
    CpuChipIcon as CpuChipM,
    WrenchScrewdriverIcon as WrenchScrewdriverM,
    ServerStackIcon as ServerStackM,
    DocumentArrowDownIcon as DocumentArrowDownM,
    PlusIcon as PlusM,
    ReceiptPercentIcon as ReceiptPercentM,
    InboxIcon as InboxM,
    UserPlusIcon as UserPlusM,
    DocumentIcon as DocumentM,
    ArrowUpTrayIcon as ArrowUpTrayM,
    ChatBubbleLeftIcon as ChatBubbleLeftM,
    TrashIcon as TrashM,
    FingerPrintIcon as FingerPrintM,
    QrCodeIcon as QrCodeM,
    DocumentDuplicateIcon as DocumentDuplicateM,
    ArrowUturnLeftIcon as ArrowUturnLeftM,
} from '@heroicons/react/20/solid';
import {
    HomeIcon as HomeU,
    Squares2X2Icon as Squares2X2U,
    PlusCircleIcon as PlusCircleU,
    TagIcon as TagU,
    ArrowDownTrayIcon as ArrowDownTrayU,
    DocumentTextIcon as DocumentTextU,
    UsersIcon as UsersU,
    ChartBarIcon as ChartBarU,
    BanknotesIcon as BanknotesU,
    StarIcon as StarU,
    IdentificationIcon as IdentificationU,
    InboxArrowDownIcon as InboxArrowDownU,
    CheckBadgeIcon as CheckBadgeU,
    FlagIcon as FlagU,
    EyeIcon as EyeU,
    EyeSlashIcon as EyeSlashU,
    ArrowPathIcon as ArrowPathU,
    CreditCardIcon as CreditCardU,
    Cog6ToothIcon as Cog6ToothU,
    ClipboardDocumentListIcon as ClipboardDocumentListU,
    AcademicCapIcon as AcademicCapU,
    CalendarIcon as CalendarU,
    BellIcon as BellU,
    UserIcon as UserU,
    BriefcaseIcon as BriefcaseU,
    ShieldCheckIcon as ShieldCheckU,
    MagnifyingGlassIcon as MagnifyingGlassU,
    ArrowRightStartOnRectangleIcon as ArrowRightStartOnRectangleU,
    Bars3Icon as Bars3U,
    XMarkIcon as XMarkU,
    ChevronRightIcon as ChevronRightU,
    ChevronDownIcon as ChevronDownU,
    InformationCircleIcon as InformationCircleU,
    CheckIcon as CheckU,
    CheckCircleIcon as CheckCircleU,
    ArrowRightIcon as ArrowRightU,
    ArrowLeftIcon as ArrowLeftU,
    ClockIcon as ClockU,
    ExclamationTriangleIcon as ExclamationTriangleU,
    XCircleIcon as XCircleU,
    LockClosedIcon as LockClosedU,
    RectangleStackIcon as RectangleStackU,
    SignalIcon as SignalU,
    ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareU,
    ChatBubbleLeftRightIcon as ChatBubbleLeftRightU,
    KeyIcon as KeyU,
    UserGroupIcon as UserGroupU,
    CpuChipIcon as CpuChipU,
    WrenchScrewdriverIcon as WrenchScrewdriverU,
    ServerStackIcon as ServerStackU,
    DocumentArrowDownIcon as DocumentArrowDownU,
    PlusIcon as PlusU,
    ReceiptPercentIcon as ReceiptPercentU,
    InboxIcon as InboxU,
    UserPlusIcon as UserPlusU,
    DocumentIcon as DocumentU,
    ArrowUpTrayIcon as ArrowUpTrayU,
    ChatBubbleLeftIcon as ChatBubbleLeftU,
    TrashIcon as TrashU,
    FingerPrintIcon as FingerPrintU,
    QrCodeIcon as QrCodeU,
    DocumentDuplicateIcon as DocumentDuplicateU,
    ArrowUturnLeftIcon as ArrowUturnLeftU,
} from '@heroicons/react/16/solid';

export const ICONS = {
    'home': { outline: HomeO, mini: HomeM, micro: HomeU },
    'squares-2x2': { outline: Squares2X2O, mini: Squares2X2M, micro: Squares2X2U },
    'plus-circle': { outline: PlusCircleO, mini: PlusCircleM, micro: PlusCircleU },
    'tag': { outline: TagO, mini: TagM, micro: TagU },
    'arrow-down-tray': { outline: ArrowDownTrayO, mini: ArrowDownTrayM, micro: ArrowDownTrayU },
    'document-text': { outline: DocumentTextO, mini: DocumentTextM, micro: DocumentTextU },
    'users': { outline: UsersO, mini: UsersM, micro: UsersU },
    'chart-bar': { outline: ChartBarO, mini: ChartBarM, micro: ChartBarU },
    'banknotes': { outline: BanknotesO, mini: BanknotesM, micro: BanknotesU },
    'star': { outline: StarO, mini: StarM, micro: StarU },
    'identification': { outline: IdentificationO, mini: IdentificationM, micro: IdentificationU },
    'inbox-arrow-down': { outline: InboxArrowDownO, mini: InboxArrowDownM, micro: InboxArrowDownU },
    'check-badge': { outline: CheckBadgeO, mini: CheckBadgeM, micro: CheckBadgeU },
    'flag': { outline: FlagO, mini: FlagM, micro: FlagU },
    'eye': { outline: EyeO, mini: EyeM, micro: EyeU },
    'eye-slash': { outline: EyeSlashO, mini: EyeSlashM, micro: EyeSlashU },
    'arrow-path': { outline: ArrowPathO, mini: ArrowPathM, micro: ArrowPathU },
    'credit-card': { outline: CreditCardO, mini: CreditCardM, micro: CreditCardU },
    'cog-6-tooth': { outline: Cog6ToothO, mini: Cog6ToothM, micro: Cog6ToothU },
    'clipboard-document-list': { outline: ClipboardDocumentListO, mini: ClipboardDocumentListM, micro: ClipboardDocumentListU },
    'academic-cap': { outline: AcademicCapO, mini: AcademicCapM, micro: AcademicCapU },
    'calendar': { outline: CalendarO, mini: CalendarM, micro: CalendarU },
    'bell': { outline: BellO, mini: BellM, micro: BellU },
    'user': { outline: UserO, mini: UserM, micro: UserU },
    'briefcase': { outline: BriefcaseO, mini: BriefcaseM, micro: BriefcaseU },
    'shield-check': { outline: ShieldCheckO, mini: ShieldCheckM, micro: ShieldCheckU },
    'magnifying-glass': { outline: MagnifyingGlassO, mini: MagnifyingGlassM, micro: MagnifyingGlassU },
    'arrow-right-start-on-rectangle': { outline: ArrowRightStartOnRectangleO, mini: ArrowRightStartOnRectangleM, micro: ArrowRightStartOnRectangleU },
    'bars-3': { outline: Bars3O, mini: Bars3M, micro: Bars3U },
    'x-mark': { outline: XMarkO, mini: XMarkM, micro: XMarkU },
    'chevron-right': { outline: ChevronRightO, mini: ChevronRightM, micro: ChevronRightU },
    'chevron-down': { outline: ChevronDownO, mini: ChevronDownM, micro: ChevronDownU },
    'information-circle': { outline: InformationCircleO, mini: InformationCircleM, micro: InformationCircleU },
    'check': { outline: CheckO, mini: CheckM, micro: CheckU },
    'check-circle': { outline: CheckCircleO, mini: CheckCircleM, micro: CheckCircleU },
    'arrow-right': { outline: ArrowRightO, mini: ArrowRightM, micro: ArrowRightU },
    'arrow-left': { outline: ArrowLeftO, mini: ArrowLeftM, micro: ArrowLeftU },
    'clock': { outline: ClockO, mini: ClockM, micro: ClockU },
    'exclamation-triangle': { outline: ExclamationTriangleO, mini: ExclamationTriangleM, micro: ExclamationTriangleU },
    'x-circle': { outline: XCircleO, mini: XCircleM, micro: XCircleU },
    'lock-closed': { outline: LockClosedO, mini: LockClosedM, micro: LockClosedU },
    'rectangle-stack': { outline: RectangleStackO, mini: RectangleStackM, micro: RectangleStackU },
    'signal': { outline: SignalO, mini: SignalM, micro: SignalU },
    'arrow-top-right-on-square': { outline: ArrowTopRightOnSquareO, mini: ArrowTopRightOnSquareM, micro: ArrowTopRightOnSquareU },
    'chat-bubble-left-right': { outline: ChatBubbleLeftRightO, mini: ChatBubbleLeftRightM, micro: ChatBubbleLeftRightU },
    'key': { outline: KeyO, mini: KeyM, micro: KeyU },
    'user-group': { outline: UserGroupO, mini: UserGroupM, micro: UserGroupU },
    'cpu-chip': { outline: CpuChipO, mini: CpuChipM, micro: CpuChipU },
    'wrench-screwdriver': { outline: WrenchScrewdriverO, mini: WrenchScrewdriverM, micro: WrenchScrewdriverU },
    'server-stack': { outline: ServerStackO, mini: ServerStackM, micro: ServerStackU },
    'document-arrow-down': { outline: DocumentArrowDownO, mini: DocumentArrowDownM, micro: DocumentArrowDownU },
    'plus': { outline: PlusO, mini: PlusM, micro: PlusU },
    'receipt-percent': { outline: ReceiptPercentO, mini: ReceiptPercentM, micro: ReceiptPercentU },
    'inbox': { outline: InboxO, mini: InboxM, micro: InboxU },
    'user-plus': { outline: UserPlusO, mini: UserPlusM, micro: UserPlusU },
    'document': { outline: DocumentO, mini: DocumentM, micro: DocumentU },
    'arrow-up-tray': { outline: ArrowUpTrayO, mini: ArrowUpTrayM, micro: ArrowUpTrayU },
    'chat-bubble-left': { outline: ChatBubbleLeftO, mini: ChatBubbleLeftM, micro: ChatBubbleLeftU },
    'trash': { outline: TrashO, mini: TrashM, micro: TrashU },
    'finger-print': { outline: FingerPrintO, mini: FingerPrintM, micro: FingerPrintU },
    'qr-code': { outline: QrCodeO, mini: QrCodeM, micro: QrCodeU },
    'document-duplicate': { outline: DocumentDuplicateO, mini: DocumentDuplicateM, micro: DocumentDuplicateU },
    'arrow-uturn-left': { outline: ArrowUturnLeftO, mini: ArrowUturnLeftM, micro: ArrowUturnLeftU },
};
